# Generated by Django 5.1.1 on 2024-09-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Image', models.ImageField(max_length=50, upload_to='')),
                ('Email', models.EmailField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Number', models.BigIntegerField(max_length=50)),
            ],
        ),
    ]
