# Generated by Django 5.1.1 on 2024-09-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Number',
            field=models.BigIntegerField(max_length=11),
        ),
    ]
