# Generated by Django 5.1.1 on 2024-09-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Number',
            field=models.BigIntegerField(),
        ),
    ]
